 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
        res.sendFile(process.cwd() + '/views/index.html');
    });

app.use(function(req, res, next){
  var potentialDate = req.path.substring(1);
  var result = {
    "unix": null,
    "natural": null
  };
  var potentialTimestamp = parseInt(potentialDate);
  if (!isNaN(potentialTimestamp)) {
    var actualDate = new Date(potentialTimestamp);
    var dateString = actualDate.toDateString();
    if (dateString !== 'Invalid Date') {
      result.unix = potentialTimestamp;
      result.natural = dateString;
    }
  } else {
    potentialDate = potentialDate.replace(/%20/gi, ' ');
    if (!isNaN(Date.parse(potentialDate))) {
      var actualDate = new Date(potentialDate);
      result.unix = actualDate.getTime();
      result.natural = potentialDate;
    }
  }
  res.end(JSON.stringify(result));
  /*res.status(404);
  res.type('txt').send('Not found');*/
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

